In [1]:
kare=lambda i:i**2

In [2]:
kare(16)

256

### map ve filter

map; Bir fonksiyonu bir listedeki her bir nesneye uygulamak için kullanılır. İki adet parametresi bulunur; kullanılacak fonkisyon ve fonksiyonun uygulanacağı dizi. "map" fonksiyonu doğrudan yazdırılabilir bir fonksiyon olmadığından genellikle listeye çevrilir.

In [3]:
liste1=list(range(1,101))

map(fonksiyon_adi,liste_adi)

In [4]:
map(kare,liste1)

In [5]:
liste2=list(map(kare,liste1))

In [6]:
print(liste2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


filter; filtreleme için kullanılır. Genellikle belirli bir şartı sağlayan değerleri elde etmek için kullanılmaktadır.

filter(fonksiyon,dizi)

In [7]:
def çift(i):
    if i%2==0:
        return i

In [8]:
çift(18)

18

In [9]:
çift(19)

In [10]:
def çift(i):
    if i%2==0:
        return True
    else:
        return False

In [12]:
çift(19)

False

In [13]:
çift(18)

True

In [14]:
çift1=lambda i:i%2==0

In [15]:
çift1(8)

True

In [16]:
çift1(9)

False

In [17]:
print(liste1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [18]:
filter(lambda i:i%2==0,liste1)

In [22]:
liste3=list(filter(lambda i:i%2==0,liste1))

In [23]:
print(liste3)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [24]:
liste4=list(filter(lambda i:i%7==0,list(range(0,1001))))

In [25]:
print(liste4)

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357, 364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448, 455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539, 546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777, 784, 791, 798, 805, 812, 819, 826, 833, 840, 847, 854, 861, 868, 875, 882, 889, 896, 903, 910, 917, 924, 931, 938, 945, 952, 959, 966, 973, 980, 987, 994]


In [26]:
liste5=["Adana","Ankara","Balıkesir","Bolu","Bursa"]

In [27]:
il=list(filter(lambda i:len(i)>5,liste5))

In [28]:
print(il)

['Ankara', 'Balıkesir']


### Lokal ve Global Kapsamlar

Lokal kapsam bir fonksiyon içinde tanımlanan nesnelerdir. Lokal kapsamda bulunan nesneler sadece fonksiyon içinde kullanılır. Fonksiyonun işlevi bittiğide bu nesneler yeniden çağrılmaz. Global kapsam ise yazılan programın ana gövdesinden erişilebilen, bir program dosyasının en üst seviyesinde olan nesnelerdir. Gömülü kapsam; Python ile önceden tanımlanmış gömülü nesne/fonksiyonlardır.

In [32]:
x=25
def çıktı():
    x=1000
    return x

In [33]:
print(x)

25


In [34]:
print(çıktı())

1000


# Dosya Okuma

open

open("c:\python1\dosya.txt","r")

open("c:\python1\dosya.txt","w")

open("c:\python1\dosya.txt","a")

In [35]:
open("c:\dosya.txt","w")

PermissionError: [Errno 13] Permission denied: 'c:\\dosya.txt'

c'nin altında python1 isimli klasör yaratılacak. Bilgisayar --> C: --> Yeni --> Yeni Klasör -->F2 python1 

In [1]:
d1=open("c:\python1\d1.txt","w")

In [2]:
d1.close()

In [3]:
with open("c:\python1\d2.txt","w") as d2:
    print(d2.read())

UnsupportedOperation: not readable

In [4]:
with open("c:\python1\d2.txt","r") as d2:
    print(d2.read())

In [5]:
with open("c:\python1\d3.txt","r") as d3:
    print(d3.read())

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\python1\\d3.txt'

write --> dosyaya yazmak için kullanılır.

In [7]:
with open("c:\python1\d2.txt","w") as d2:
    d2.write("Python ilk yazım")
    d2.close()

In [8]:
with open("c:\python1\d3.txt","w",encoding="utf-8") as d3:
    d3.write("Python ilk yazım, ç ö ş")
    d3.close()

In [9]:
with open("c:\python1\d2.txt","w") as d2:
    d2.write("4 Ağustos 2022 Saat 10:56")
    d2.close()

In [10]:
with open("c:\python1\d3.txt","a",encoding="utf-8") as d3:
    d3.write("4. Gün Eğitimi")
    d3.close()

In [11]:
with open("c:\python1\d3.txt","a",encoding="utf-8") as d3:
    d3.write("\n 4 Ağustos 2022")
    d3.close()

### Dosya okuma

In [13]:
d4=open("c:\python1\d3.txt","r",encoding="utf-8")
icerik=d4.read()
print(icerik)
d4.close()

Python ilk yazım, ç ö ş4. Gün Eğitimi
 4 Ağustos 2022


readline / readlines

In [19]:
d4=open("c:\python1\d3.txt","r",encoding="utf-8")
icerik=d4.readline()
print(icerik)
d4.close()

Python ilk yazım, ç ö ş4. Gün Eğitimi



### Dosyada değişiklik yapma

In [20]:
with open("c:\python1\d3.txt","r+",encoding="utf-8") as d3:
    bilgi=d3.read()
    bilgi="Perşembe\n"+bilgi
    d3.seek(0)
    d3.write(bilgi)

In [21]:
with open("c:\python1\d3.txt","r+",encoding="utf-8") as d3:
    bilgi=d3.read()
    bilgi=bilgi+"\nPerşembe"
    d3.seek(0)
    d3.write(bilgi)

In [22]:
with open("c:\python1\d3.txt","r+",encoding="utf-8") as d3:
    içerik=d3.readlines()
    içerik.insert(2,"Python 2022")
    d3.seek(0)
    d3.writelines(içerik)

## Bazı Temel Fonksiyonlar

abs; mutlak değer almaya yarar

In [23]:
abs(-1999)

1999

round; sayıyı yuvarlamak için kullanılır.

In [24]:
round(19.2)

19

In [25]:
round(19.8)

20

In [26]:
round(3.13267891,3)

3.133

max ve min; max en büyük, min en küçük değeri verir.

In [27]:
max(100,-3,15.9,7)

100

In [28]:
min(100,-3,15.9,7)

-3

sum; verilen değerleri toplamaya yarar.

In [29]:
sum([1,2,3,4,5])

15

In [30]:
sum((1,2,3,4,5))

15

pow; verilen değerin dilendiği şeklinde üssünü alır.

In [31]:
pow(2,2)

4

In [32]:
pow(2,5)

32

# Numpy & Pandas

## Numpy

Numpy, bir doğrusal cebir modülüdür. Veri madenciliği, makine öğrenmesi ve veri analizi için sıklıkla kullanlmaktadır. Tek ve çok boyutlu diziler bulunmaktadır ve "array" isimli dizilerin elemanlarına ulaşmak kolay olup, bu dizilerele birçok metot ve fonksiyon kullanılabilir.

In [33]:
import numpy as np

In [34]:
veri1=list(range(1,11))

In [35]:
print(veri1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
dizi1=np.array(veri1)

In [38]:
print(dizi1)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
type(dizi1)

numpy.ndarray

In [40]:
veri2=[[1,2,3],[4,5,6],[7,8,9]]

In [41]:
seri2=np.array(veri2)

In [42]:
print(seri2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
veri3=np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [44]:
print(veri3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(veri1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [46]:
veri1[0]

1

In [47]:
veri1[3]

4

In [48]:
print(veri3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
veri3[2,2]

9

In [50]:
veri3[4,4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [51]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
d1=np.arange(10,21)

In [53]:
print(d1)

[10 11 12 13 14 15 16 17 18 19 20]


In [54]:
np.arange(10,100,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])

In [59]:
np.zeros((10,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
np.ones((10,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [64]:
np.ones((3,10,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1

In [65]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### Rassal Sayı Üretme

In [66]:
np.random.randint(0,100)

75

In [67]:
np.random.randint(100)

61

In [68]:
np.random.randint(1,1000,5)

array([171,  46, 505, 302, 966])

In [69]:
np.random.rand(100)

array([0.69949569, 0.6198882 , 0.21306103, 0.99861543, 0.25819169,
       0.60333851, 0.11662396, 0.02442975, 0.27515799, 0.38909185,
       0.21149697, 0.11644891, 0.88163021, 0.47998521, 0.40692298,
       0.20690855, 0.83453947, 0.2109805 , 0.11614985, 0.0474784 ,
       0.84355336, 0.48169052, 0.20653743, 0.757144  , 0.52227123,
       0.94160953, 0.3165375 , 0.2832678 , 0.45462358, 0.62245693,
       0.77703486, 0.40595157, 0.70233493, 0.97778941, 0.91406668,
       0.34468212, 0.034538  , 0.69253212, 0.16793445, 0.30653062,
       0.16951696, 0.39880975, 0.2893723 , 0.7054978 , 0.69630644,
       0.3625847 , 0.18717829, 0.99107233, 0.26918681, 0.85348247,
       0.36328737, 0.84569547, 0.53878854, 0.57455621, 0.29984427,
       0.77081834, 0.34607181, 0.24839463, 0.6939781 , 0.97690474,
       0.31903349, 0.44414504, 0.55215325, 0.69030196, 0.62595544,
       0.1578668 , 0.53337074, 0.0825404 , 0.07745539, 0.03602777,
       0.5252519 , 0.62551707, 0.90736517, 0.19637369, 0.08630

In [70]:
np.random.randn(100)

array([ 0.29358154, -0.94568506,  0.88147766,  0.92864755,  1.44204656,
        0.70067373, -1.09537051, -0.11123535, -0.66426237,  0.33500337,
        1.23557217,  0.89662025, -0.47084353,  1.42001042,  0.73562799,
        0.69433824, -0.78658852, -0.61892786, -0.60560385, -0.35491162,
        2.15123308,  0.46868047,  0.32592485,  0.5307974 ,  0.34476091,
       -3.32742282,  0.6973667 ,  1.64850819,  0.46582544,  0.118366  ,
        1.82049639,  1.66767474,  1.08592666, -0.44489735,  0.11945844,
       -0.11026724, -0.55429964,  0.09380553,  0.4797824 ,  2.31601986,
       -0.13875558, -1.0158207 , -0.12661109, -0.93800219, -0.1734317 ,
        0.06970112, -0.21749431, -1.00435194,  0.26807605,  1.04438762,
        0.66505855,  0.84732044, -1.69073552,  0.68903126, -0.14777736,
        0.15317209, -0.33244841,  0.88677128, -0.86069842, -1.42660595,
       -0.30998192, -0.60891923, -0.16733703, -0.08576493,  0.10667381,
       -1.28313321,  0.94019135, -1.14194268,  1.07893725, -0.56

### Dizi Şekillendirme

In [71]:
d3=np.arange(25)

In [72]:
print(d3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [75]:
d4=d3.reshape(5,5)

In [74]:
print(d3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [76]:
print(d4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Bazı popüler fonksiyonlar

In [78]:
d5=np.random.randint(1,1001,100)

In [79]:
print(d5)

[676 305 293  31 498 756 104 569 607 120 498 668 709 187 929 619 318 116
 446 454 718 508 464 792 767 502 304 502 999 159 661  36 890 992 325 445
 276 133 770 279 686 687  72 373 812 524 618 718 736 393 919 819 999 991
 983  25 420 631  65 482 252 448 230 557  82 685 734 475 437 834 678 319
 791 182 927 235 137 869 833 929 738 532 591 616 513 301 394 417 116 159
 134 598 405 949 333 660 888 538 322 143]


In [80]:
d5.max()

999

In [81]:
d5.min()

25

In [82]:
d5.sum()

51359

In [83]:
d5.mean()

513.59

In [86]:
d5.argmax()

28

In [85]:
d5.argmin()

55

In [87]:
d6=d5.reshape(10,10)

In [88]:
print(d6)

[[676 305 293  31 498 756 104 569 607 120]
 [498 668 709 187 929 619 318 116 446 454]
 [718 508 464 792 767 502 304 502 999 159]
 [661  36 890 992 325 445 276 133 770 279]
 [686 687  72 373 812 524 618 718 736 393]
 [919 819 999 991 983  25 420 631  65 482]
 [252 448 230 557  82 685 734 475 437 834]
 [678 319 791 182 927 235 137 869 833 929]
 [738 532 591 616 513 301 394 417 116 159]
 [134 598 405 949 333 660 888 538 322 143]]


In [89]:
np.linalg.det(d6)

-7.09385411176455e+27

### Dizilerin İndekslenmesi

In [90]:
d7=np.arange(1,21)

In [91]:
d7[1]

2

In [92]:
print(d7)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [93]:
d7[1:4]

array([2, 3, 4])

In [94]:
d7[:4]

array([1, 2, 3, 4])

In [95]:
d7[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [97]:
d7[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [98]:
d7[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [99]:
d7[4]=9999

In [100]:
print(d7)

[   1    2    3    4 9999    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20]


In [101]:
d7[:4]=11111111

In [102]:
print(d7)

[11111111 11111111 11111111 11111111     9999        6        7        8
        9       10       11       12       13       14       15       16
       17       18       19       20]


In [103]:
d8=np.arange(1,21)

In [104]:
print(d8)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [105]:
d8=d8.reshape(4,5)

In [106]:
print(d8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [107]:
d8[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [108]:
d8[:2,:2]

array([[1, 2],
       [6, 7]])

In [109]:
d8[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [110]:
print(d8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [111]:
d8[d8>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [112]:
d9=d8[d8>8]

In [113]:
print(d9)

[ 9 10 11 12 13 14 15 16 17 18 19 20]


In [114]:
s1=np.array([1,2,3,4,5])

In [115]:
s2=np.array([10,20,30,40,50])

In [116]:
s2+s1

array([11, 22, 33, 44, 55])

In [117]:
s1*s2

array([ 10,  40,  90, 160, 250])

In [119]:
s1+100

array([101, 102, 103, 104, 105])

In [120]:
s1/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [121]:
s2**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

In [122]:
np.sqrt(s2)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

## Pandas

Panda, veri işleme, temizleme ve analizi için kullanılır. Seri ve veri çerçevesi bulunmaktadır. Farklı kaynaklardan verilerle çalışılabilir.

In [123]:
import pandas as pd

In [124]:
isim=["A","B","C","D","E"]

In [125]:
sayi=[1,2,3,4,5]

In [126]:
pd.Series(data=sayi,index=isim)

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [129]:
a=pd.Series(sayi, isim)

In [130]:
print(a)

A    1
B    2
C    3
D    4
E    5
dtype: int64


In [131]:
type(a)

pandas.core.series.Series

In [132]:
sd1=np.array([1,2,3,4,5])

In [133]:
pd.Series(sd1)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [134]:
pd.Series(data=sd1,index=["A","B","C","D","E"])

A    1
B    2
C    3
D    4
E    5
dtype: int32

In [136]:
sozluk1={"A":10,"B":20,"C":40,"D":50,"E":60}

In [137]:
print(sozluk1)

{'A': 10, 'B': 20, 'C': 40, 'D': 50, 'E': 60}


In [138]:
type(sozluk1)

dict

In [139]:
pd.Series(sozluk1)

A    10
B    20
C    40
D    50
E    60
dtype: int64

In [140]:
p1=pd.Series(sozluk1)

In [141]:
p2=pd.Series([2,4,6,8,10],["X","Y","Z","W","Q"])

In [142]:
print(p2)

X     2
Y     4
Z     6
W     8
Q    10
dtype: int64


In [143]:
p1+p2

A   NaN
B   NaN
C   NaN
D   NaN
E   NaN
Q   NaN
W   NaN
X   NaN
Y   NaN
Z   NaN
dtype: float64

NaN= Not a Number

In [144]:
p3=pd.Series([2,4,6,8,10],["A","B","C","D","E"])

In [145]:
p1+p3

A    12
B    24
C    46
D    58
E    70
dtype: int64

In [148]:
toplam=p1+p3

In [149]:
print(toplam)

A    12
B    24
C    46
D    58
E    70
dtype: int64


In [ ]:
toplam["F"]